//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentDailyHour
    {
        public int AgentDailyHoursID { get; set; }
        public int EmployeeID { get; set; }
        public byte DomainMasterID { get; set; }
        public System.DateTime LoginTimeStamp { get; set; }
        public System.DateTime LogoutTimeStamp { get; set; }
        public System.TimeSpan LoginDuration { get; set; }
        public Nullable<short> AgentTimeAdjustmentReasonID { get; set; }
        public Nullable<short> PayPeriodID { get; set; }
        public Nullable<decimal> RegularHours { get; set; }
        public Nullable<decimal> OverTimeHours { get; set; }
    
        public virtual DomainMaster DomainMaster { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual AgentTimeAdjustmentReason AgentTimeAdjustmentReason { get; set; }
        public virtual PayPeriod PayPeriod { get; set; }
    }
}
