//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentDailyHour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentDailyHour()
        {
            this.AgentDailyHoursToDomainMasters = new HashSet<AgentDailyHoursToDomainMaster>();
        }
    
        public int AgentDailyHoursID { get; set; }
        public int EmployeeID { get; set; }
        public byte DomainMasterID { get; set; }
        public System.DateTime LoginTimeStamp { get; set; }
        public System.DateTime LogoutTimeStamp { get; set; }
        public System.TimeSpan LoginDuration { get; set; }
        public Nullable<short> AgentTimeAdjustmentReasonID { get; set; }
        public Nullable<short> PayPeriodID { get; set; }
        public Nullable<decimal> RegularHours { get; set; }
        public Nullable<decimal> OverTimeHours { get; set; }
        public Nullable<int> EditByEmployeeID { get; set; }
        public Nullable<System.DateTime> EditTimeStamp { get; set; }
    
        public virtual DomainMaster DomainMaster { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual AgentTimeAdjustmentReason AgentTimeAdjustmentReason { get; set; }
        public virtual PayPeriod PayPeriod { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentDailyHoursToDomainMaster> AgentDailyHoursToDomainMasters { get; set; }
    }
}
