//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentDailyHoursToDomainMaster
    {
        public int AgentDailyHoursID { get; set; }
        public byte DomainMasterID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long ID { get; set; }
    
        public virtual DomainMaster DomainMaster { get; set; }
        public virtual AgentDailyHour AgentDailyHour { get; set; }
    }
}
