//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerKey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnswerKey()
        {
            this.CFRInsurances = new HashSet<CFRInsurance>();
            this.CFRInsurances1 = new HashSet<CFRInsurance>();
            this.CFRInsurances2 = new HashSet<CFRInsurance>();
            this.CFRInsurances3 = new HashSet<CFRInsurance>();
            this.CFRInsurances4 = new HashSet<CFRInsurance>();
            this.CFRInsurances5 = new HashSet<CFRInsurance>();
            this.CFRInsurances6 = new HashSet<CFRInsurance>();
            this.CFRInsurances7 = new HashSet<CFRInsurance>();
            this.CFRInsurances8 = new HashSet<CFRInsurance>();
            this.CFRInsurances9 = new HashSet<CFRInsurance>();
            this.CFRInsurances10 = new HashSet<CFRInsurance>();
            this.CFRInsurances11 = new HashSet<CFRInsurance>();
            this.CFRInsurances12 = new HashSet<CFRInsurance>();
            this.CFRInsurances13 = new HashSet<CFRInsurance>();
            this.CFRInsurances14 = new HashSet<CFRInsurance>();
            this.CFRInsurances15 = new HashSet<CFRInsurance>();
            this.CFRInsurances16 = new HashSet<CFRInsurance>();
            this.CFRInsurances17 = new HashSet<CFRInsurance>();
            this.CFRInsurances18 = new HashSet<CFRInsurance>();
            this.CFRInsurances19 = new HashSet<CFRInsurance>();
            this.CFRMortgages = new HashSet<CFRMortgage>();
            this.CFRMortgages1 = new HashSet<CFRMortgage>();
            this.CFRMortgages2 = new HashSet<CFRMortgage>();
            this.CFRMortgages3 = new HashSet<CFRMortgage>();
            this.CFRMortgages4 = new HashSet<CFRMortgage>();
            this.CFRMortgages5 = new HashSet<CFRMortgage>();
            this.CFRMortgages6 = new HashSet<CFRMortgage>();
            this.CFRMortgages7 = new HashSet<CFRMortgage>();
            this.CFRMortgages8 = new HashSet<CFRMortgage>();
            this.CFRMortgages9 = new HashSet<CFRMortgage>();
            this.CFRMortgages10 = new HashSet<CFRMortgage>();
            this.CFRMortgages11 = new HashSet<CFRMortgage>();
            this.CFRMortgages12 = new HashSet<CFRMortgage>();
            this.CFRMortgages13 = new HashSet<CFRMortgage>();
            this.CFRMortgages14 = new HashSet<CFRMortgage>();
            this.CFRMortgages15 = new HashSet<CFRMortgage>();
            this.CFRMortgages16 = new HashSet<CFRMortgage>();
            this.CFRMortgages17 = new HashSet<CFRMortgage>();
            this.CFRMortgages18 = new HashSet<CFRMortgage>();
            this.CFRPatientRecruitments = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments1 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments2 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments3 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments4 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments5 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments6 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments7 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments8 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments9 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments10 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments11 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments12 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments13 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments14 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments15 = new HashSet<CFRPatientRecruitment>();
            this.CFRPatientRecruitments16 = new HashSet<CFRPatientRecruitment>();
            this.CFRSales = new HashSet<CFRSale>();
            this.CFRSales1 = new HashSet<CFRSale>();
            this.CFRSales2 = new HashSet<CFRSale>();
            this.CFRSales3 = new HashSet<CFRSale>();
            this.CFRSales4 = new HashSet<CFRSale>();
            this.CFRSales5 = new HashSet<CFRSale>();
            this.CFRSales6 = new HashSet<CFRSale>();
            this.CFRSales7 = new HashSet<CFRSale>();
            this.CFRSales8 = new HashSet<CFRSale>();
            this.CFRSales9 = new HashSet<CFRSale>();
            this.CFRSales10 = new HashSet<CFRSale>();
            this.CFRSales11 = new HashSet<CFRSale>();
            this.CFRSales12 = new HashSet<CFRSale>();
            this.CFRSales13 = new HashSet<CFRSale>();
            this.CFRAcurians = new HashSet<CFRAcurian>();
            this.CFRAcurians1 = new HashSet<CFRAcurian>();
            this.CFRAcurians2 = new HashSet<CFRAcurian>();
            this.CFRAcurians3 = new HashSet<CFRAcurian>();
            this.CFRAcurians4 = new HashSet<CFRAcurian>();
            this.CFRAcurians5 = new HashSet<CFRAcurian>();
            this.CFRAcurians6 = new HashSet<CFRAcurian>();
            this.CFRAcurians7 = new HashSet<CFRAcurian>();
            this.CFRAcurians8 = new HashSet<CFRAcurian>();
            this.CFRAcurians9 = new HashSet<CFRAcurian>();
            this.CFRAcurians10 = new HashSet<CFRAcurian>();
            this.CFRAcurians11 = new HashSet<CFRAcurian>();
            this.CFRAcurians12 = new HashSet<CFRAcurian>();
            this.CFRAcurians13 = new HashSet<CFRAcurian>();
            this.CFRAcurians14 = new HashSet<CFRAcurian>();
            this.CFRAcurians15 = new HashSet<CFRAcurian>();
            this.CFRAcurians16 = new HashSet<CFRAcurian>();
            this.CFRAcurians17 = new HashSet<CFRAcurian>();
            this.CFRAcurians18 = new HashSet<CFRAcurian>();
            this.CFRAcurians19 = new HashSet<CFRAcurian>();
            this.CFRAcurians20 = new HashSet<CFRAcurian>();
            this.CFRAcurians21 = new HashSet<CFRAcurian>();
            this.CFRAcurians22 = new HashSet<CFRAcurian>();
            this.CFRAcurians23 = new HashSet<CFRAcurian>();
            this.CFRAcurians24 = new HashSet<CFRAcurian>();
            this.CFRAcurians25 = new HashSet<CFRAcurian>();
            this.CFRAcurians26 = new HashSet<CFRAcurian>();
            this.CFRAcurians27 = new HashSet<CFRAcurian>();
            this.CFRAcurians28 = new HashSet<CFRAcurian>();
        }
    
        public int AnswerKeyID { get; set; }
        public string AnswerOption { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRInsurance> CFRInsurances19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRMortgage> CFRMortgages18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRPatientRecruitment> CFRPatientRecruitments16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRSale> CFRSales13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFRAcurian> CFRAcurians28 { get; set; }
    }
}
