//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFRAcurian
    {
        public int CFRAcurianID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<byte> DomainMasterID { get; set; }
        public short C_Calls { get; set; }
        public Nullable<int> aIQ1 { get; set; }
        public Nullable<int> aIQ2 { get; set; }
        public Nullable<int> aIQ3 { get; set; }
        public Nullable<int> aCSQ1 { get; set; }
        public Nullable<int> aCSQ2 { get; set; }
        public Nullable<int> aCSQ3 { get; set; }
        public Nullable<int> aCSQ4 { get; set; }
        public Nullable<int> aCSQ5 { get; set; }
        public Nullable<int> aCSQ6 { get; set; }
        public Nullable<int> aCSQ7 { get; set; }
        public Nullable<int> aSSQ1 { get; set; }
        public Nullable<int> aSSQ2 { get; set; }
        public Nullable<int> aSSQ3 { get; set; }
        public Nullable<int> aSSQ4 { get; set; }
        public Nullable<int> aSSQ5 { get; set; }
        public Nullable<int> aSSQ6 { get; set; }
        public Nullable<int> aSSQ7 { get; set; }
        public Nullable<int> aSSQ8 { get; set; }
        public Nullable<int> aCOQ1 { get; set; }
        public Nullable<int> aCOQ2 { get; set; }
        public Nullable<int> aCOQ3 { get; set; }
        public Nullable<int> aCOQ4 { get; set; }
        public Nullable<int> aCOQ5 { get; set; }
        public Nullable<int> aCOQ6 { get; set; }
        public Nullable<int> aCOQ7 { get; set; }
        public Nullable<int> aCOQ8 { get; set; }
        public Nullable<int> aCLQ1 { get; set; }
        public Nullable<int> aCLQ2 { get; set; }
        public Nullable<int> aCLQ3 { get; set; }
        public Nullable<int> IntroductionRating { get; set; }
        public Nullable<int> CommunicationSkillsRating { get; set; }
        public Nullable<int> SoftSkillsRating { get; set; }
        public Nullable<int> ComplianceRating { get; set; }
        public Nullable<int> ClosingRating { get; set; }
        public string ConversionRateToday { get; set; }
        public string WeekToDate { get; set; }
        public string Comments { get; set; }
        public string Strengths { get; set; }
        public string ActionPlan { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public System.DateTime DateOfFeedback { get; set; }
    
        public virtual DomainMaster DomainMaster { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual AnswerKey AnswerKey { get; set; }
        public virtual AnswerKey AnswerKey1 { get; set; }
        public virtual AnswerKey AnswerKey2 { get; set; }
        public virtual AnswerKey AnswerKey3 { get; set; }
        public virtual AnswerKey AnswerKey4 { get; set; }
        public virtual AnswerKey AnswerKey5 { get; set; }
        public virtual AnswerKey AnswerKey6 { get; set; }
        public virtual AnswerKey AnswerKey7 { get; set; }
        public virtual AnswerKey AnswerKey8 { get; set; }
        public virtual AnswerKey AnswerKey9 { get; set; }
        public virtual AnswerKey AnswerKey10 { get; set; }
        public virtual AnswerKey AnswerKey11 { get; set; }
        public virtual AnswerKey AnswerKey12 { get; set; }
        public virtual AnswerKey AnswerKey13 { get; set; }
        public virtual AnswerKey AnswerKey14 { get; set; }
        public virtual AnswerKey AnswerKey15 { get; set; }
        public virtual AnswerKey AnswerKey16 { get; set; }
        public virtual AnswerKey AnswerKey17 { get; set; }
        public virtual AnswerKey AnswerKey18 { get; set; }
        public virtual AnswerKey AnswerKey19 { get; set; }
        public virtual AnswerKey AnswerKey20 { get; set; }
        public virtual AnswerKey AnswerKey21 { get; set; }
        public virtual AnswerKey AnswerKey22 { get; set; }
        public virtual AnswerKey AnswerKey23 { get; set; }
        public virtual AnswerKey AnswerKey24 { get; set; }
        public virtual AnswerKey AnswerKey25 { get; set; }
        public virtual AnswerKey AnswerKey26 { get; set; }
        public virtual AnswerKey AnswerKey27 { get; set; }
        public virtual AnswerKey AnswerKey28 { get; set; }
        public virtual CFRPerformanceAnalysi CFRPerformanceAnalysi { get; set; }
        public virtual CFRPerformanceAnalysi CFRPerformanceAnalysi1 { get; set; }
        public virtual CFRPerformanceAnalysi CFRPerformanceAnalysi2 { get; set; }
        public virtual CFRPerformanceAnalysi CFRPerformanceAnalysi3 { get; set; }
        public virtual CFRPerformanceAnalysi CFRPerformanceAnalysi4 { get; set; }
    }
}
