//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DomainType()
        {
            this.DomainMasters = new HashSet<DomainMaster>();
        }
    
        public byte DomainTypeID { get; set; }
        public string DomainTypeName { get; set; }
        public string DomainTypeDescription { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.TimeSpan AddTime { get; set; }
        public int AddByEmployeeID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DeactiveDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomainMaster> DomainMasters { get; set; }
    }
}
