//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreedomDailyPortfolioInventory
    {
        public System.DateTime ReportDate { get; set; }
        public string LeadID { get; set; }
        public string ListName { get; set; }
        public string Status { get; set; }
        public string State { get; set; }
        public string CurrentDisposition { get; set; }
        public string LastCallDay { get; set; }
        public string LastCallTime { get; set; }
        public string CampaignName { get; set; }
    }
}
