//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayPeriod()
        {
            this.EmployeeHoursTotals = new HashSet<EmployeeHoursTotal>();
            this.AgentDailyHours = new HashSet<AgentDailyHour>();
        }
    
        public short PayPeriodID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime MidDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime PayDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeHoursTotal> EmployeeHoursTotals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentDailyHour> AgentDailyHours { get; set; }
    }
}
