//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPeriod
    {
        public long PayPeriodID { get; set; }
        public byte DomainMasterID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime StartPeriod { get; set; }
        public System.DateTime MidPeriod { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime PayDate { get; set; }
    
        public virtual DomainMaster DomainMaster { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
