//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreciseLeadsHourlyCallLogMaster
    {
        public System.DateTime RecordDate { get; set; }
        public System.TimeSpan RecordTime { get; set; }
        public string DomainName { get; set; }
        public string Five9Timestamp { get; set; }
        public string CampaignName { get; set; }
        public string CallType { get; set; }
        public string AgentID { get; set; }
        public string Disposition { get; set; }
        public string AutomaticNumberIdentification { get; set; }
        public string LeadID { get; set; }
        public string CustomerName { get; set; }
        public string DialedNumberIdentificationService { get; set; }
        public string CallTime { get; set; }
        public string BillTimeRounded { get; set; }
        public string Cost { get; set; }
        public string IVRTime { get; set; }
        public string QueueWaitTime { get; set; }
        public string RingTime { get; set; }
        public string TalkTime { get; set; }
        public string HoldTime { get; set; }
        public string ParkTime { get; set; }
        public string AfterCallWorkTime { get; set; }
        public string Transfers { get; set; }
        public string Conferences { get; set; }
        public string Holds { get; set; }
        public string Abandonded { get; set; }
        public string Recordings { get; set; }
        public string CallDayOfMonth { get; set; }
        public string CallDayOfWeek { get; set; }
        public string CallHourOfDay { get; set; }
        public string AbandonRate { get; set; }
        public string ANIAreaCode { get; set; }
        public string ANICountry { get; set; }
        public string ANICountryCode { get; set; }
        public string ANIState { get; set; }
        public string Calls { get; set; }
        public string CallsCompletedInIVR { get; set; }
        public string CallsTimedOutInIVR { get; set; }
        public string CampaignType { get; set; }
        public string Contacted { get; set; }
        public Nullable<bool> DisconnectedFromHold { get; set; }
        public string DNISAreaCode { get; set; }
        public string DNISCountry { get; set; }
        public string DNISCountryCode { get; set; }
        public string DNISState { get; set; }
        public string ListName { get; set; }
        public string LiveConnect { get; set; }
        public string NoPartyContact { get; set; }
        public string Notes { get; set; }
        public string ServiceLevel { get; set; }
        public string Skill { get; set; }
        public string SpeedOfAnswer { get; set; }
        public string ThirdPartyTalkTime { get; set; }
        public string ConferenceTime { get; set; }
        public string ConsultTime { get; set; }
        public string DialTime { get; set; }
        public string HandleTime { get; set; }
        public string ManualTime { get; set; }
        public string Rate { get; set; }
        public string TalkTimeLessHoldAndPark { get; set; }
        public string TimeToAbandon { get; set; }
        public string AgentEmail { get; set; }
        public string AgentFirstName { get; set; }
        public string AgentLastName { get; set; }
        public string Extension { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string IsDoNotCall { get; set; }
        public string ContactID { get; set; }
        public string CallID { get; set; }
        public string AgentGroup { get; set; }
        public string SessionID { get; set; }
        public string ParentSessionID { get; set; }
        public string ClientID { get; set; }
        public string CustomerEmailAddress { get; set; }
        public string InputWebsite { get; set; }
        public string SourceID { get; set; }
    }
}
