//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemMaster
    {
        public long ProblemID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string UserID { get; set; }
        public string ProcessName { get; set; }
        public int ErrorNumber { get; set; }
        public int LineNumber { get; set; }
        public string ExceptionMessage { get; set; }
        public string ExceptionSource { get; set; }
        public int ExceptionSeverity { get; set; }
        public int ExceptionState { get; set; }
        public bool IsResolved { get; set; }
        public System.DateTime ResolvedDate { get; set; }
        public int ResolvedByEmployeeID { get; set; }
    }
}
