//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_TestProject.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportEntities : DbContext
    {
        public ReportEntities()
            : base("name=ReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<DomainMaster> DomainMasters { get; set; }
        public virtual DbSet<DomainType> DomainTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeFive9Agent> EmployeeFive9Agent { get; set; }
        public virtual DbSet<EmployeeNote> EmployeeNotes { get; set; }
        public virtual DbSet<EmployeeNoteType> EmployeeNoteTypes { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<ProblemMaster> ProblemMasters { get; set; }
        public virtual DbSet<CampaignGroup> CampaignGroups { get; set; }
        public virtual DbSet<DailyPortfolioInventory> DailyPortfolioInventories { get; set; }
        public virtual DbSet<CallLogMaster> CallLogMasters { get; set; }
        public virtual DbSet<PreciseLeadsHourlyCampaignMetric> PreciseLeadsHourlyCampaignMetrics { get; set; }
        public virtual DbSet<PreciseLeadsRollingCampaignMetric> PreciseLeadsRollingCampaignMetrics { get; set; }
        public virtual DbSet<FreedomHourlyCallMetric> FreedomHourlyCallMetrics { get; set; }
        public virtual DbSet<AgentDailyHour> AgentDailyHours { get; set; }
        public virtual DbSet<CallLogMaster1> CallLogMaster1 { get; set; }
        public virtual DbSet<ClientLead> ClientLeads { get; set; }
        public virtual DbSet<FreedomDailyPortfolioInventory> FreedomDailyPortfolioInventories { get; set; }
        public virtual DbSet<FreedomHourlyCallMetrics1> FreedomHourlyCallMetrics1 { get; set; }
        public virtual DbSet<PreciseLeadsHourlyCallLogMaster> PreciseLeadsHourlyCallLogMasters { get; set; }
    }
}
